set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

set-option -g base-index 1
set-option -g pane-base-index 1

bind ß move-window -r

set-option -g mouse on

set-option -g history-limit 100000

set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -s focus-events on
set-option -s extended-keys on
set-option -s escape-time 0


setw -g mode-keys vi

# ~/.tmux.conf
set -g prefix C-a
bind C-a send-prefix


# Im Copy-Mode: y kopiert Auswahl ins Windows-Clipboard und beendet Copy-Mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"
# Windows-Clipboard in tmux einf├╝gen (Ctrl+A + p)
bind-key p run-shell "powershell.exe -NoProfile -Command Get-Clipboard | tr -d '\r' | tmux load-buffer - && tmux paste-buffer"

